services:
  - type: web
    name: maisha-uni-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maisha_uni_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DEBUG
        value: false

databases:
  - name: maisha_uni_db
    plan: free